import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import Overlay from "@/components/Overlay";
import NavClient from "@/components/NavClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background text-foreground font-noto-serif`}
      >
        <div className="root flex w-full h-screen">
          <Suspense>
            <NavClient />
          </Suspense>

          <div id="main" className="w-full overflow-y-scroll">
            <Overlay />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
