import type { Metadata } from "next";
import "./globals.css";
import NavDataContainer from "@/components/NavDataContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-background text-foreground`}>
        <div className="root flex w-screen">
          <NavDataContainer />
          {children}
        </div>
      </body>
    </html>
  );
}
